version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: lost_and_found_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: zhoma005
      POSTGRES_DB: lost_and_found
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
    driver: local
